language: generic
language: ruby
rvm:
  - 2.4.4

script:
   - chmod +x build-gh-pages.sh && ./build-gh-pages.sh

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: built
  on:
    branch: master
